/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Experiment */
        post: operations["create_experiment_api_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_api_experiments__experiment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Experiment */
        post: operations["stop_experiment_api_experiments__experiment_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Experiment */
        post: operations["pause_experiment_api_experiments__experiment_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Experiment */
        post: operations["resume_experiment_api_experiments__experiment_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Experiment Speed */
        post: operations["set_experiment_speed_api_experiments__experiment_id__speed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stream Frame Schema
         * @description Never called by any client. Its only purpose is to make StreamFrame's
         *     discriminated union appear in /openapi.json, which is what pulls the
         *     WebSocket payload shapes into the generated TypeScript types
         *     (SPEC §1 decision 4).
         */
        get: operations["get_stream_frame_schema_api_schema_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EdgeView */
        EdgeView: {
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /**
         * Event
         * @description Emitted, ordered, streamable.
         */
        Event: {
            /** Sim Tick */
            sim_tick: number;
            event_type: components["schemas"]["EventType"];
            /** Agent Id */
            agent_id?: string | null;
            /** Source Agent Id */
            source_agent_id?: string | null;
            /** Target Agent Id */
            target_agent_id?: string | null;
            /** Risk Score */
            risk_score?: number | null;
            /** Metadata */
            metadata?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Seq */
            seq: number;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Wall Time
             * Format: date-time
             */
            wall_time: string;
        };
        /** EventFrame */
        EventFrame: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "event";
            event: components["schemas"]["Event"];
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "EXPERIMENT_STARTED" | "EXPERIMENT_STOPPED" | "AGENT_CREATED" | "AGENT_STARTED" | "AGENT_STOPPED" | "MESSAGE_SENT" | "MESSAGE_RECEIVED" | "MODEL_REQUESTED" | "MODEL_RESPONDED" | "TOOL_REQUESTED" | "TOOL_EXECUTED" | "TOOL_DENIED" | "MEMORY_READ" | "MEMORY_WRITE" | "CREDENTIAL_ACCESSED" | "CREDENTIAL_REVOKED" | "COMPROMISE_ATTEMPTED" | "COMPROMISE_SUCCEEDED" | "COMPROMISE_FAILED" | "ANOMALY_DETECTED" | "AGENT_QUARANTINED" | "AGENT_RELEASED" | "PERMISSION_CHANGED" | "INFERENCE_DISABLED" | "THREAT_SIGNATURE_PUBLISHED" | "THREAT_SIGNATURE_RECEIVED" | "AGENT_RECOVERED";
        /** ExperimentConfig */
        ExperimentConfig: {
            /** Seed */
            seed: number;
            /**
             * Node Count
             * @default 60
             */
            node_count: number;
            /**
             * Edge Density
             * @default 2
             */
            edge_density: number;
            /**
             * Software Type Count
             * @default 3
             */
            software_type_count: number;
            /**
             * P Same
             * @default 0.15
             */
            p_same: number;
            /**
             * P Cross
             * @default 0.03
             */
            p_cross: number;
            /**
             * Max Ticks
             * @default 200
             */
            max_ticks: number;
            /**
             * Detector Sensitivity
             * @default 0.2
             */
            detector_sensitivity: number;
            /**
             * Defense Enabled
             * @default true
             */
            defense_enabled: boolean;
            /**
             * Initial Compromised
             * @default highest_degree
             * @enum {string}
             */
            initial_compromised: "highest_degree" | "random_node";
        };
        /** ExperimentSummary */
        ExperimentSummary: {
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "paused" | "finished" | "stopped";
            /** Sim Tick */
            sim_tick: number;
            config: components["schemas"]["ExperimentConfig"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        JsonValue: unknown;
        /** NodeView */
        NodeView: {
            /** Id */
            id: string;
            /** Software Type */
            software_type: string;
            security_state: components["schemas"]["SecurityState"];
            /** Compromised By */
            compromised_by?: string | null;
            /** Tick Compromised */
            tick_compromised?: number | null;
        };
        /**
         * SecurityState
         * @enum {string}
         */
        SecurityState: "healthy" | "suspicious" | "compromised" | "quarantined" | "recovered";
        /** SnapshotFrame */
        SnapshotFrame: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "snapshot";
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /** Last Seq */
            last_seq: number;
            /** Sim Tick */
            sim_tick: number;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "paused" | "finished" | "stopped";
            /** Nodes */
            nodes: components["schemas"]["NodeView"][];
            /** Edges */
            edges: components["schemas"]["EdgeView"][];
        };
        /** SpeedRequest */
        SpeedRequest: {
            /** Multiplier */
            multiplier: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_experiment_api_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_api_experiments__experiment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_experiment_api_experiments__experiment_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_experiment_api_experiments__experiment_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_experiment_api_experiments__experiment_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_experiment_speed_api_experiments__experiment_id__speed_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stream_frame_schema_api_schema_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotFrame"] | components["schemas"]["EventFrame"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
